/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 5.1 */
/* Tue Aug 05 00:00:20 2014 */

/* parameterized module instance */
biosrom __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
